### ISSUE TITLE
[CTD] Crash with Minecolonies Supply camp preview

### ISSUE THREAD

**Issue by drakray** [Minecraft-LightLand/L2Hostility#2]
https://pastebin.com/WMQCnFbb

Technically Structurize mod, but still
Happens with the Fortress Supply Camp

<details> <summary>Crash snippet</summary>

```
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.m_151559_()" because the return value of "net.minecraft.world.level.chunk.LevelChunk.m_62953_()" is null
	at dev.xkmc.l2hostility.content.capability.chunk.ChunkDifficulty.init(ChunkDifficulty.java:96) ~[l2hostility-2.4.10.jar%23759!/:2.4.10] {re:classloading}
	at dev.xkmc.l2hostility.content.capability.chunk.ChunkDifficultyCap.<init>(ChunkDifficultyCap.java:24) ~[l2hostility-2.4.10.jar%23759!/:2.4.10] {re:classloading}
	at dev.xkmc.l2hostility.events.CapabilityEvents.onAttachChunkCapabilities(CapabilityEvents.java:56) ~[l2hostility-2.4.10.jar%23759!/:2.4.10] {re:classloading}
	at dev.xkmc.l2hostility.events.__CapabilityEvents_onAttachChunkCapabilities_AttachCapabilitiesEvent.invoke(.dynamic) ~[l2hostility-2.4.10.jar%23759!/:2.4.10] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2389!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2389!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2389!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:634) ~[forge-1.20.1-47.1.79-universal.jar%23841!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:628) ~[forge-1.20.1-47.1.79-universal.jar%23841!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraftforge.common.capabilities.CapabilityProvider.doGatherCapabilities(CapabilityProvider.java:72) ~[forge-1.20.1-47.1.79-universal.jar%23841!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:67) ~[forge-1.20.1-47.1.79-universal.jar%23841!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:51) ~[forge-1.20.1-47.1.79-universal.jar%23841!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider$AsField.initInternal(CapabilityProvider.java:208) ~[forge-1.20.1-47.1.79-universal.jar%23841!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk.<init>(LevelChunk.java:97) ~[client-1.20.1-20230612.114412-srg.jar%23836!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:instancemanage.InstanceAddMixin,pl:mixin:APP:moonlight-common.mixins.json:LevelChunkMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.LevelChunk.<init>(LevelChunk.java:80) ~[client-1.20.1-20230612.114412-srg.jar%23836!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:instancemanage.InstanceAddMixin,pl:mixin:APP:moonlight-common.mixins.json:LevelChunkMixin,pl:mixin:A}
	at com.ldtteam.structurize.client.BlueprintChunk.<init>(BlueprintChunk.java:70) ~[1-structurize-1.20.1-1.0.659-BETA.jar%23604!/:1.20.1-1.0.659-BETA] {re:classloading}
	at com.ldtteam.structurize.client.BlueprintBlockAccess.m_6522_(BlueprintBlockAccess.java:182) ~[1-structurize-1.20.1-1.0.659-BETA.jar%23604!/:1.20.1-1.0.659-BETA] {re:classloading}
	at net.minecraft.world.level.LevelReader.m_46819_(LevelReader.java:129) ~[client-1.20.1-20230612.114412-srg.jar%23836!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.world.level.Level.m_6325_(Level.java:182) ~[client-1.20.1-20230612.114412-srg.jar%23836!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,xf:fml:beefix:Level,re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:cloud,xf:fml:beefix:Level,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,xf:fml:beefix:Level,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:create_new_age.mixins.json:LevelMixin,pl:mixin:APP:the_bumblezone-common.mixins.json:world.LevelMixin,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:APP:aether.mixins.json:common.accessor.LevelAccessor,pl:mixin:APP:xycraft_core.mixin.json:LevelRainShieldMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_6325_(Level.java:73) ~[client-1.20.1-20230612.114412-srg.jar%23836!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,xf:fml:beefix:Level,re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:cloud,xf:fml:beefix:Level,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,xf:fml:beefix:Level,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:create_new_age.mixins.json:LevelMixin,pl:mixin:APP:the_bumblezone-common.mixins.json:world.LevelMixin,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:APP:aether.mixins.json:common.accessor.LevelAccessor,pl:mixin:APP:xycraft_core.mixin.json:LevelRainShieldMixin,pl:mixin:A}
	at net.minecraft.world.level.LevelReader.m_46865_(LevelReader.java:121) ~[client-1.20.1-20230612.114412-srg.jar%23836!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114457_(EntityRenderDispatcher.java:273) ~[client-1.20.1-20230612.114412-srg.jar%23836!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:renderer,xf:fml:twilightforest:bake,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:renderer,xf:fml:twilightforest:bake,pl:mixin:APP:playerAnimator-common.mixins.json:firstPerson.EntityRenderDispatcherMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:150) ~[client-1.20.1-20230612.114412-srg.jar%23836!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:renderer,xf:fml:twilightforest:bake,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:renderer,xf:fml:twilightforest:bake,pl:mixin:APP:playerAnimator-common.mixins.json:firstPerson.EntityRenderDispatcherMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.ldtteam.structurize.client.BlueprintRenderer.draw(BlueprintRenderer.java:373) ~[1-structurize-1.20.1-1.0.659-BETA.jar%23604!/:1.20.1-1.0.659-BETA] {re:classloading}
	at com.ldtteam.structurize.client.BlueprintHandler.draw(BlueprintHandler.java:81) ~[1-structurize-1.20.1-1.0.659-BETA.jar%23604!/:1.20.1-1.0.659-BETA] {re:classloading}
	at com.ldtteam.structurize.event.ClientEventSubscriber.renderWorldLastEvent(ClientEventSubscriber.java:98) ~[1-structurize-1.20.1-1.0.659-BETA.jar%23604!/:1.20.1-1.0.659-BETA] {re:classloading}
	at com.ldtteam.structurize.event.__ClientEventSubscriber_renderWorldLastEvent_RenderLevelStageEvent.invoke(.dynamic) ~[1-structurize-1.20.1-1.0.659-BETA.jar%23604!/:1.20.1-1.0.659-BETA] {re:classloading,pl:eventbus:B}
```

</details>

MC 1.20.1
Neoforge 47.1.79
MineColonies 1.20.1-1.1.274-BETA
Structurize 1.20.1-1.0.659-BETA
L2 Hostility 2.4.10
L2 Library 2.4.20
Buncha other mod, listed in crashLog

**Comment by Nightenom** [comment]
Yeah, this our fault, soon to be fixed in ldtteam/structurize#623
